Добавил требования к программе
it-top-shambala/Planner pull request #3
Opened 2024-09-20 17:27 UTC by Lexaik

2024-09-20 17:35 UTC, Ludmilka1201 approved these changes
Ок

2024-09-20 17:48 UTC, anst-foto requested changes
Переделать

2024-09-20 17:48 UTC, anst-foto commented on README.md
> ++ GUI
Уточнить требования или разделить их на категории: от заказчика, то что нужно сделать.

2024-09-23 16:20 UTC, anst-foto approved these changes
👍

2024-09-23 16:21 UTC, merged